### ISSUE TITLE
Could not download the driver!

### ISSUE THREAD

**Issue by JG4123** [R4YVEN/raybot-zero#1]
I get this error popup when running "rayzero_control.exe" from the folder loader, inside build. Is there something I am doing wrong? Building in VS22 seemed fine as I got 2 successful builds.

**Comment by emlinhax** [comment]
Im not gonna help you with this one. You can easily find the reason by doing 5 seconds of debugging.

Issue closed.

**Comment by JG4123** [comment]
Alright, but what do I do after rayzero_contro.exe loads? I manage to fix the "could not download the driver!" issue but what next? I'm stuck on this window.
![image](https://user-images.githubusercontent.com/94813156/209741227-e084de3a-a8f7-40ec-abfc-0adb9ff8402c.png)
